### ISSUE TITLE
[Feature suggestion] Option to swap behaviour on ctrl and alt

### ISSUE THREAD

**Issue by BadIdeasBureau** [ElfFriend-DnD/foundryvtt-canvasScroll#4]
Ctrl+scroll to zoom is pretty common behaviour in a lot of apps.  Having MW to pan, ctrl+MW to zoom (and then shift/alt+MW for rotation) would let Foundry match that.  Could be a toggle in the module options, rather than a default setting.

(Also, I am super happy that this supports sideways scrolling!)

**Comment by akrigline** [comment]
This is a great suggestion. I'm unfortunately deprecating this particular module (almost immediately) because this one was brought to my attention from the maker of Cursor Zoom:
https://foundryvtt.com/packages/zoom-pan-options/

I'll add this to that repo's issues though for consideration.
